name: Upload addon archive
on:
  release:
    types: [published]
jobs:
  build:
    name: TBC
    runs-on: ubuntu-latest
    steps:
      - run: wget "${{ github.event.release.assets[0].browser_download_url }}"
      - run: unzip LibEventSourcing.zip
      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          args: "-c -e -l -u -g bcc -r LibEventSourcing"

