name: Run test suite
on:
  push:
jobs:
  lint:
    name: Run luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"
      - name: Run tests
        run: lua -l tests/_bootstrap tests/*.lua
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: .
